server:
  port: 8080

resilience4j:
  retry:
    instances:
      paymentRetry:
        maxAttempts: 3
        waitDuration: 2s

  circuitbreaker:
    instances:
      paymentServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10 # Last 10 calls are monitored. Used to calculate failure rate. 
        minimumNumberOfCalls: 5 # Circuit breaker activates only after 5 calls. Prevents early wrong decisions
        failureRateThreshold: 50 # If 50% calls fail, breaker opens. Example - 5 calls → 3 failed → 60% ❌ → OPEN
        waitDurationInOpenState: 10s # Time circuit stays OPEN. After 10 seconds → HALF-OPEN
        permittedNumberOfCallsInHalfOpenState: 3 # Only 3 test calls allowed. Helps safely check recovery
        automaticTransitionFromOpenToHalfOpenEnabled: true # Automatically moves from OPEN → HALF-OPEN. Without manual trigger