events {}

http {
    upstream springboot {
        server three-tier-application:8080;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://three-tier-application:8080;
        }
    }
}