server:
  port: 8088

spring:
  cloud:
    gateway:
      routes:
        - id: USERSERVICE
          uri: lb://USERSERVICE
          predicates:
            - Path=/api/user/**
        - id: HOTELSERVICE
          uri: lb://HOTELSERVICE
          predicates:
            - Path=/hotel/api/**,/hotel/staff/** # if hmako ek se jada url ko acces karna hai to ese use karo 
        - id: RATINGSERVICE
          uri: lb://RATINGSERVICE
          predicates:
            - Path=/** # sab ke sab url ko access karna hai tho directly /** likh do  
  main:
    web-application-type: reactive
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka