spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ratingmicroservice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: RATINGSERVICE
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
 
server:
  port: 8087

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true # isko true karege and bolege ki is service ko serviceRegistry se register karo
    register-with-eureka: true # this is used to register this service with serviceRegistry
    service-url:
      defaultZone: http://localhost:8761/eureka # jis service pe register hona hai uska url provide karge yha ham
